import random
"""
This is a simple script.
The documentation will be generated by this command python -m pydoc -w main.
"""
def print_hi(name):
    """
    This function prints hi
    :param name:
    :return:
    """
    print(f'Hi, {name}')  # Press ⌘F8 to toggle the breakpoint.


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    print_hi('PyCharm')

# See PyCharm help at https://www.jetbrains.com/help/pycharm/
